// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

/**
 * Protobuf type {@code app.BatchMsg}
 */
public final class BatchMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:app.BatchMsg)
    BatchMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BatchMsg.newBuilder() to construct.
  private BatchMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BatchMsg() {
    imMessage_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BatchMsg();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BatchMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              imMessage_ = new java.util.ArrayList<ImMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            imMessage_.add(
                input.readMessage(ImMessage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        imMessage_ = java.util.Collections.unmodifiableList(imMessage_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return IMProtoc.internal_static_app_BatchMsg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return IMProtoc.internal_static_app_BatchMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BatchMsg.class, BatchMsg.Builder.class);
  }

  public static final int IMMESSAGE_FIELD_NUMBER = 1;
  private java.util.List<ImMessage> imMessage_;
  /**
   * <code>repeated .app.ImMessage imMessage = 1;</code>
   */
  @java.lang.Override
  public java.util.List<ImMessage> getImMessageList() {
    return imMessage_;
  }
  /**
   * <code>repeated .app.ImMessage imMessage = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ImMessageOrBuilder>
      getImMessageOrBuilderList() {
    return imMessage_;
  }
  /**
   * <code>repeated .app.ImMessage imMessage = 1;</code>
   */
  @java.lang.Override
  public int getImMessageCount() {
    return imMessage_.size();
  }
  /**
   * <code>repeated .app.ImMessage imMessage = 1;</code>
   */
  @java.lang.Override
  public ImMessage getImMessage(int index) {
    return imMessage_.get(index);
  }
  /**
   * <code>repeated .app.ImMessage imMessage = 1;</code>
   */
  @java.lang.Override
  public ImMessageOrBuilder getImMessageOrBuilder(
      int index) {
    return imMessage_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < imMessage_.size(); i++) {
      output.writeMessage(1, imMessage_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < imMessage_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, imMessage_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BatchMsg)) {
      return super.equals(obj);
    }
    BatchMsg other = (BatchMsg) obj;

    if (!getImMessageList()
        .equals(other.getImMessageList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getImMessageCount() > 0) {
      hash = (37 * hash) + IMMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImMessageList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BatchMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BatchMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BatchMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BatchMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BatchMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BatchMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BatchMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BatchMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static BatchMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static BatchMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BatchMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BatchMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BatchMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code app.BatchMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:app.BatchMsg)
          BatchMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMProtoc.internal_static_app_BatchMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMProtoc.internal_static_app_BatchMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BatchMsg.class, BatchMsg.Builder.class);
    }

    // Construct using com.zj.protocol.grpc.BatchMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getImMessageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (imMessageBuilder_ == null) {
        imMessage_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        imMessageBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return IMProtoc.internal_static_app_BatchMsg_descriptor;
    }

    @java.lang.Override
    public BatchMsg getDefaultInstanceForType() {
      return BatchMsg.getDefaultInstance();
    }

    @java.lang.Override
    public BatchMsg build() {
      BatchMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public BatchMsg buildPartial() {
      BatchMsg result = new BatchMsg(this);
      int from_bitField0_ = bitField0_;
      if (imMessageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          imMessage_ = java.util.Collections.unmodifiableList(imMessage_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.imMessage_ = imMessage_;
      } else {
        result.imMessage_ = imMessageBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BatchMsg) {
        return mergeFrom((BatchMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BatchMsg other) {
      if (other == BatchMsg.getDefaultInstance()) return this;
      if (imMessageBuilder_ == null) {
        if (!other.imMessage_.isEmpty()) {
          if (imMessage_.isEmpty()) {
            imMessage_ = other.imMessage_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureImMessageIsMutable();
            imMessage_.addAll(other.imMessage_);
          }
          onChanged();
        }
      } else {
        if (!other.imMessage_.isEmpty()) {
          if (imMessageBuilder_.isEmpty()) {
            imMessageBuilder_.dispose();
            imMessageBuilder_ = null;
            imMessage_ = other.imMessage_;
            bitField0_ = (bitField0_ & ~0x00000001);
            imMessageBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getImMessageFieldBuilder() : null;
          } else {
            imMessageBuilder_.addAllMessages(other.imMessage_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      BatchMsg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (BatchMsg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ImMessage> imMessage_ =
      java.util.Collections.emptyList();
    private void ensureImMessageIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        imMessage_ = new java.util.ArrayList<ImMessage>(imMessage_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<ImMessage, ImMessage.Builder, ImMessageOrBuilder> imMessageBuilder_;

    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public java.util.List<ImMessage> getImMessageList() {
      if (imMessageBuilder_ == null) {
        return java.util.Collections.unmodifiableList(imMessage_);
      } else {
        return imMessageBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public int getImMessageCount() {
      if (imMessageBuilder_ == null) {
        return imMessage_.size();
      } else {
        return imMessageBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public ImMessage getImMessage(int index) {
      if (imMessageBuilder_ == null) {
        return imMessage_.get(index);
      } else {
        return imMessageBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public Builder setImMessage(
        int index, ImMessage value) {
      if (imMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImMessageIsMutable();
        imMessage_.set(index, value);
        onChanged();
      } else {
        imMessageBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public Builder setImMessage(
        int index, ImMessage.Builder builderForValue) {
      if (imMessageBuilder_ == null) {
        ensureImMessageIsMutable();
        imMessage_.set(index, builderForValue.build());
        onChanged();
      } else {
        imMessageBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public Builder addImMessage(ImMessage value) {
      if (imMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImMessageIsMutable();
        imMessage_.add(value);
        onChanged();
      } else {
        imMessageBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public Builder addImMessage(
        int index, ImMessage value) {
      if (imMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImMessageIsMutable();
        imMessage_.add(index, value);
        onChanged();
      } else {
        imMessageBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public Builder addImMessage(
        ImMessage.Builder builderForValue) {
      if (imMessageBuilder_ == null) {
        ensureImMessageIsMutable();
        imMessage_.add(builderForValue.build());
        onChanged();
      } else {
        imMessageBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public Builder addImMessage(
        int index, ImMessage.Builder builderForValue) {
      if (imMessageBuilder_ == null) {
        ensureImMessageIsMutable();
        imMessage_.add(index, builderForValue.build());
        onChanged();
      } else {
        imMessageBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public Builder addAllImMessage(
        java.lang.Iterable<? extends ImMessage> values) {
      if (imMessageBuilder_ == null) {
        ensureImMessageIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, imMessage_);
        onChanged();
      } else {
        imMessageBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public Builder clearImMessage() {
      if (imMessageBuilder_ == null) {
        imMessage_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        imMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public Builder removeImMessage(int index) {
      if (imMessageBuilder_ == null) {
        ensureImMessageIsMutable();
        imMessage_.remove(index);
        onChanged();
      } else {
        imMessageBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public ImMessage.Builder getImMessageBuilder(
        int index) {
      return getImMessageFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public ImMessageOrBuilder getImMessageOrBuilder(
        int index) {
      if (imMessageBuilder_ == null) {
        return imMessage_.get(index);  } else {
        return imMessageBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public java.util.List<? extends ImMessageOrBuilder>
         getImMessageOrBuilderList() {
      if (imMessageBuilder_ != null) {
        return imMessageBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(imMessage_);
      }
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public ImMessage.Builder addImMessageBuilder() {
      return getImMessageFieldBuilder().addBuilder(
          ImMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public ImMessage.Builder addImMessageBuilder(
        int index) {
      return getImMessageFieldBuilder().addBuilder(
          index, ImMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .app.ImMessage imMessage = 1;</code>
     */
    public java.util.List<ImMessage.Builder>
         getImMessageBuilderList() {
      return getImMessageFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<ImMessage, ImMessage.Builder, ImMessageOrBuilder>
        getImMessageFieldBuilder() {
      if (imMessageBuilder_ == null) {
        imMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<ImMessage, ImMessage.Builder, ImMessageOrBuilder>(
                imMessage_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        imMessage_ = null;
      }
      return imMessageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:app.BatchMsg)
  }

  // @@protoc_insertion_point(class_scope:app.BatchMsg)
  private static final BatchMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BatchMsg();
  }

  public static BatchMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchMsg>
      PARSER = new com.google.protobuf.AbstractParser<BatchMsg>() {
    @java.lang.Override
    public BatchMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BatchMsg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BatchMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatchMsg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public BatchMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

