// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

public interface BatchMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:app.BatchMsg)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .app.ImMessage imMessage = 1;</code>
   */
  java.util.List<ImMessage>
      getImMessageList();
  /**
   * <code>repeated .app.ImMessage imMessage = 1;</code>
   */
  ImMessage getImMessage(int index);
  /**
   * <code>repeated .app.ImMessage imMessage = 1;</code>
   */
  int getImMessageCount();
}
