// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

public interface CCVideoContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:app.CCVideoContent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string videoId = 1;</code>
   * @return The videoId.
   */
  java.lang.String getVideoId();
  /**
   * <code>string videoId = 1;</code>
   * @return The bytes for videoId.
   */
  com.google.protobuf.ByteString
      getVideoIdBytes();
}
