// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

public interface GetImMessageReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:app.GetImMessageReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 groupId = 1;</code>
   * @return The groupId.
   */
  long getGroupId();

  /**
   * <code>uint64 ownerId = 2;</code>
   * @return The ownerId.
   */
  long getOwnerId();
}
