// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

public interface ImgContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:app.ImgContent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>uint32 height = 2;</code>
   * @return The height.
   */
  int getHeight();

  /**
   * <code>uint32 width = 3;</code>
   * @return The width.
   */
  int getWidth();
}
