// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

public interface ImMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:app.ImMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 groupId = 1;</code>
   */
  long getGroupId();

  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 ownerId = 2;</code>
   */
  long getOwnerId();

  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 sendTime = 3;</code>
   */
  long getSendTime();

  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 msgId = 4;</code>
   */
  long getMsgId();

  /**
   * <code>optional string clientMsgId = 5;</code>
   */
  java.lang.String getClientMsgId();
  /**
   * <code>optional string clientMsgId = 5;</code>
   */
  com.google.protobuf.ByteString
      getClientMsgIdBytes();

  /**
   * <code>optional string msgType = 6;</code>
   */
  java.lang.String getMsgType();
  /**
   * <code>optional string msgType = 6;</code>
   */
  com.google.protobuf.ByteString
      getMsgTypeBytes();

  /**
   * <code>optional .app.ImgContent imgContent = 7;</code>
   */
  boolean hasImgContent();
  /**
   * <code>optional .app.ImgContent imgContent = 7;</code>
   */
  ImgContent getImgContent();

  /**
   * <code>optional .app.VideoContent videoContent = 8;</code>
   */
  boolean hasVideoContent();
  /**
   * <code>optional .app.VideoContent videoContent = 8;</code>
   */
  VideoContent getVideoContent();

  /**
   * <code>optional .app.TextContent textContent = 9;</code>
   */
  boolean hasTextContent();
  /**
   * <code>optional .app.TextContent textContent = 9;</code>
   */
  TextContent getTextContent();

  /**
   * <code>optional .app.AudioContent audioContent = 10;</code>
   */
  boolean hasAudioContent();
  /**
   * <code>optional .app.AudioContent audioContent = 10;</code>
   */
  AudioContent getAudioContent();

  /**
   * <code>optional .app.CCVideoContent ccVideoContent = 11;</code>
   */
  boolean hasCcVideoContent();
  /**
   * <code>optional .app.CCVideoContent ccVideoContent = 11;</code>
   */
  CCVideoContent getCcVideoContent();

  /**
   * <code>optional .app.QuestionContent questionContent = 12;</code>
   */
  boolean hasQuestionContent();
  /**
   * <code>optional .app.QuestionContent questionContent = 12;</code>
   */
  QuestionContent getQuestionContent();

  /**
   * <code>optional .app.SenderInfo sender = 13;</code>
   */
  boolean hasSender();
  /**
   * <code>optional .app.SenderInfo sender = 13;</code>
   */
  SenderInfo getSender();

  /**
   * <code>optional uint64 replyMsgId = 14;</code>
   */
  long getReplyMsgId();

  /**
   * <code>optional .app.ImMessage replyMsg = 15;</code>
   */
  boolean hasReplyMsg();
  /**
   * <code>optional .app.ImMessage replyMsg = 15;</code>
   */
  ImMessage getReplyMsg();
}
