// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

public interface ImMessageReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:app.ImMessageReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.app.ImMessageReq.Op op = 1;</code>
   * @return The enum numeric value on the wire for op.
   */
  int getOpValue();
  /**
   * <code>.app.ImMessageReq.Op op = 1;</code>
   * @return The op.
   */
  ImMessageReq.Op getOp();

  /**
   * <code>uint64 groupId = 2;</code>
   * @return The groupId.
   */
  long getGroupId();

  /**
   * <code>uint64 ownerId = 3;</code>
   * @return The ownerId.
   */
  long getOwnerId();

  /**
   * <code>uint64 targetUserId = 4;</code>
   * @return The targetUserId.
   */
  long getTargetUserId();

  /**
   * <code>string channel = 5;</code>
   * @return The channel.
   */
  java.lang.String getChannel();
  /**
   * <code>string channel = 5;</code>
   * @return The bytes for channel.
   */
  com.google.protobuf.ByteString
      getChannelBytes();

  /**
   * <code>string seq = 6;</code>
   * @return The seq.
   */
  java.lang.String getSeq();
  /**
   * <code>string seq = 6;</code>
   * @return The bytes for seq.
   */
  com.google.protobuf.ByteString
      getSeqBytes();
}
