// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

/**
 * Protobuf type {@code app.ImMessageReply}
 */
public final class ImMessageReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:app.ImMessageReply)
    ImMessageReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ImMessageReply.newBuilder() to construct.
  private ImMessageReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ImMessageReply() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ImMessageReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ImMessageReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ImMessage.Builder subBuilder = null;
            if (imMessage_ != null) {
              subBuilder = imMessage_.toBuilder();
            }
            imMessage_ = input.readMessage(ImMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(imMessage_);
              imMessage_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            ImMessageReply.ReqContext.Builder subBuilder = null;
            if (reqContext_ != null) {
              subBuilder = reqContext_.toBuilder();
            }
            reqContext_ = input.readMessage(ImMessageReply.ReqContext.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(reqContext_);
              reqContext_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            type_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return IMProtoc.internal_static_app_ImMessageReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return IMProtoc.internal_static_app_ImMessageReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ImMessageReply.class, ImMessageReply.Builder.class);
  }

  public interface ReqContextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:app.ImMessageReply.ReqContext)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 groupId = 2;</code>
     * @return The groupId.
     */
    long getGroupId();

    /**
     * <code>uint64 ownerId = 3;</code>
     * @return The ownerId.
     */
    long getOwnerId();

    /**
     * <code>uint64 targetUserId = 4;</code>
     * @return The targetUserId.
     */
    long getTargetUserId();

    /**
     * <code>string channel = 5;</code>
     * @return The channel.
     */
    java.lang.String getChannel();
    /**
     * <code>string channel = 5;</code>
     * @return The bytes for channel.
     */
    com.google.protobuf.ByteString
        getChannelBytes();

    /**
     * <code>string seq = 6;</code>
     * @return The seq.
     */
    java.lang.String getSeq();
    /**
     * <code>string seq = 6;</code>
     * @return The bytes for seq.
     */
    com.google.protobuf.ByteString
        getSeqBytes();
  }
  /**
   * Protobuf type {@code app.ImMessageReply.ReqContext}
   */
  public static final class ReqContext extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:app.ImMessageReply.ReqContext)
      ReqContextOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqContext.newBuilder() to construct.
    private ReqContext(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqContext() {
      channel_ = "";
      seq_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReqContext();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqContext(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {

              groupId_ = input.readUInt64();
              break;
            }
            case 24: {

              ownerId_ = input.readUInt64();
              break;
            }
            case 32: {

              targetUserId_ = input.readUInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              channel_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              seq_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMProtoc.internal_static_app_ImMessageReply_ReqContext_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMProtoc.internal_static_app_ImMessageReply_ReqContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ImMessageReply.ReqContext.class, ImMessageReply.ReqContext.Builder.class);
    }

    public static final int GROUPID_FIELD_NUMBER = 2;
    private long groupId_;
    /**
     * <code>uint64 groupId = 2;</code>
     * @return The groupId.
     */
    @java.lang.Override
    public long getGroupId() {
      return groupId_;
    }

    public static final int OWNERID_FIELD_NUMBER = 3;
    private long ownerId_;
    /**
     * <code>uint64 ownerId = 3;</code>
     * @return The ownerId.
     */
    @java.lang.Override
    public long getOwnerId() {
      return ownerId_;
    }

    public static final int TARGETUSERID_FIELD_NUMBER = 4;
    private long targetUserId_;
    /**
     * <code>uint64 targetUserId = 4;</code>
     * @return The targetUserId.
     */
    @java.lang.Override
    public long getTargetUserId() {
      return targetUserId_;
    }

    public static final int CHANNEL_FIELD_NUMBER = 5;
    private volatile java.lang.Object channel_;
    /**
     * <code>string channel = 5;</code>
     * @return The channel.
     */
    @java.lang.Override
    public java.lang.String getChannel() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channel_ = s;
        return s;
      }
    }
    /**
     * <code>string channel = 5;</code>
     * @return The bytes for channel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChannelBytes() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQ_FIELD_NUMBER = 6;
    private volatile java.lang.Object seq_;
    /**
     * <code>string seq = 6;</code>
     * @return The seq.
     */
    @java.lang.Override
    public java.lang.String getSeq() {
      java.lang.Object ref = seq_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        seq_ = s;
        return s;
      }
    }
    /**
     * <code>string seq = 6;</code>
     * @return The bytes for seq.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSeqBytes() {
      java.lang.Object ref = seq_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        seq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (groupId_ != 0L) {
        output.writeUInt64(2, groupId_);
      }
      if (ownerId_ != 0L) {
        output.writeUInt64(3, ownerId_);
      }
      if (targetUserId_ != 0L) {
        output.writeUInt64(4, targetUserId_);
      }
      if (!getChannelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, channel_);
      }
      if (!getSeqBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, seq_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (groupId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, groupId_);
      }
      if (ownerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, ownerId_);
      }
      if (targetUserId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, targetUserId_);
      }
      if (!getChannelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, channel_);
      }
      if (!getSeqBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, seq_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ImMessageReply.ReqContext)) {
        return super.equals(obj);
      }
      ImMessageReply.ReqContext other = (ImMessageReply.ReqContext) obj;

      if (getGroupId()
          != other.getGroupId()) return false;
      if (getOwnerId()
          != other.getOwnerId()) return false;
      if (getTargetUserId()
          != other.getTargetUserId()) return false;
      if (!getChannel()
          .equals(other.getChannel())) return false;
      if (!getSeq()
          .equals(other.getSeq())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGroupId());
      hash = (37 * hash) + OWNERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOwnerId());
      hash = (37 * hash) + TARGETUSERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTargetUserId());
      hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getChannel().hashCode();
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + getSeq().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ImMessageReply.ReqContext parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImMessageReply.ReqContext parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImMessageReply.ReqContext parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImMessageReply.ReqContext parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImMessageReply.ReqContext parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImMessageReply.ReqContext parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImMessageReply.ReqContext parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImMessageReply.ReqContext parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImMessageReply.ReqContext parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ImMessageReply.ReqContext parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImMessageReply.ReqContext parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImMessageReply.ReqContext parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ImMessageReply.ReqContext prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code app.ImMessageReply.ReqContext}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:app.ImMessageReply.ReqContext)
        ImMessageReply.ReqContextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IMProtoc.internal_static_app_ImMessageReply_ReqContext_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IMProtoc.internal_static_app_ImMessageReply_ReqContext_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ImMessageReply.ReqContext.class, ImMessageReply.ReqContext.Builder.class);
      }

      // Construct using com.zj.protocol.grpc.ImMessageReply.ReqContext.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        groupId_ = 0L;

        ownerId_ = 0L;

        targetUserId_ = 0L;

        channel_ = "";

        seq_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IMProtoc.internal_static_app_ImMessageReply_ReqContext_descriptor;
      }

      @java.lang.Override
      public ImMessageReply.ReqContext getDefaultInstanceForType() {
        return ImMessageReply.ReqContext.getDefaultInstance();
      }

      @java.lang.Override
      public ImMessageReply.ReqContext build() {
        ImMessageReply.ReqContext result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ImMessageReply.ReqContext buildPartial() {
        ImMessageReply.ReqContext result = new ImMessageReply.ReqContext(this);
        result.groupId_ = groupId_;
        result.ownerId_ = ownerId_;
        result.targetUserId_ = targetUserId_;
        result.channel_ = channel_;
        result.seq_ = seq_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ImMessageReply.ReqContext) {
          return mergeFrom((ImMessageReply.ReqContext)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ImMessageReply.ReqContext other) {
        if (other == ImMessageReply.ReqContext.getDefaultInstance()) return this;
        if (other.getGroupId() != 0L) {
          setGroupId(other.getGroupId());
        }
        if (other.getOwnerId() != 0L) {
          setOwnerId(other.getOwnerId());
        }
        if (other.getTargetUserId() != 0L) {
          setTargetUserId(other.getTargetUserId());
        }
        if (!other.getChannel().isEmpty()) {
          channel_ = other.channel_;
          onChanged();
        }
        if (!other.getSeq().isEmpty()) {
          seq_ = other.seq_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ImMessageReply.ReqContext parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ImMessageReply.ReqContext) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long groupId_ ;
      /**
       * <code>uint64 groupId = 2;</code>
       * @return The groupId.
       */
      @java.lang.Override
      public long getGroupId() {
        return groupId_;
      }
      /**
       * <code>uint64 groupId = 2;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(long value) {
        
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 groupId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        
        groupId_ = 0L;
        onChanged();
        return this;
      }

      private long ownerId_ ;
      /**
       * <code>uint64 ownerId = 3;</code>
       * @return The ownerId.
       */
      @java.lang.Override
      public long getOwnerId() {
        return ownerId_;
      }
      /**
       * <code>uint64 ownerId = 3;</code>
       * @param value The ownerId to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerId(long value) {
        
        ownerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 ownerId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerId() {
        
        ownerId_ = 0L;
        onChanged();
        return this;
      }

      private long targetUserId_ ;
      /**
       * <code>uint64 targetUserId = 4;</code>
       * @return The targetUserId.
       */
      @java.lang.Override
      public long getTargetUserId() {
        return targetUserId_;
      }
      /**
       * <code>uint64 targetUserId = 4;</code>
       * @param value The targetUserId to set.
       * @return This builder for chaining.
       */
      public Builder setTargetUserId(long value) {
        
        targetUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 targetUserId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetUserId() {
        
        targetUserId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object channel_ = "";
      /**
       * <code>string channel = 5;</code>
       * @return The channel.
       */
      public java.lang.String getChannel() {
        java.lang.Object ref = channel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          channel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string channel = 5;</code>
       * @return The bytes for channel.
       */
      public com.google.protobuf.ByteString
          getChannelBytes() {
        java.lang.Object ref = channel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string channel = 5;</code>
       * @param value The channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string channel = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannel() {
        
        channel_ = getDefaultInstance().getChannel();
        onChanged();
        return this;
      }
      /**
       * <code>string channel = 5;</code>
       * @param value The bytes for channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channel_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object seq_ = "";
      /**
       * <code>string seq = 6;</code>
       * @return The seq.
       */
      public java.lang.String getSeq() {
        java.lang.Object ref = seq_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          seq_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string seq = 6;</code>
       * @return The bytes for seq.
       */
      public com.google.protobuf.ByteString
          getSeqBytes() {
        java.lang.Object ref = seq_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          seq_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string seq = 6;</code>
       * @param value The seq to set.
       * @return This builder for chaining.
       */
      public Builder setSeq(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string seq = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeq() {
        
        seq_ = getDefaultInstance().getSeq();
        onChanged();
        return this;
      }
      /**
       * <code>string seq = 6;</code>
       * @param value The bytes for seq to set.
       * @return This builder for chaining.
       */
      public Builder setSeqBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        seq_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:app.ImMessageReply.ReqContext)
    }

    // @@protoc_insertion_point(class_scope:app.ImMessageReply.ReqContext)
    private static final ImMessageReply.ReqContext DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ImMessageReply.ReqContext();
    }

    public static ImMessageReply.ReqContext getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqContext>
        PARSER = new com.google.protobuf.AbstractParser<ReqContext>() {
      @java.lang.Override
      public ReqContext parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqContext(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqContext> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqContext> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ImMessageReply.ReqContext getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_;
  /**
   * <pre>
   **
   * 0 代表是消息 1 代表是服务器收到请求的回执
   * </pre>
   *
   * <code>int32 type = 3;</code>
   * @return The type.
   */
  @java.lang.Override
  public int getType() {
    return type_;
  }

  public static final int IMMESSAGE_FIELD_NUMBER = 1;
  private ImMessage imMessage_;
  /**
   * <code>.app.ImMessage imMessage = 1;</code>
   * @return Whether the imMessage field is set.
   */
  @java.lang.Override
  public boolean hasImMessage() {
    return imMessage_ != null;
  }
  /**
   * <code>.app.ImMessage imMessage = 1;</code>
   * @return The imMessage.
   */
  @java.lang.Override
  public ImMessage getImMessage() {
    return imMessage_ == null ? ImMessage.getDefaultInstance() : imMessage_;
  }
  /**
   * <code>.app.ImMessage imMessage = 1;</code>
   */
  @java.lang.Override
  public ImMessageOrBuilder getImMessageOrBuilder() {
    return getImMessage();
  }

  public static final int REQCONTEXT_FIELD_NUMBER = 2;
  private ImMessageReply.ReqContext reqContext_;
  /**
   * <code>.app.ImMessageReply.ReqContext reqContext = 2;</code>
   * @return Whether the reqContext field is set.
   */
  @java.lang.Override
  public boolean hasReqContext() {
    return reqContext_ != null;
  }
  /**
   * <code>.app.ImMessageReply.ReqContext reqContext = 2;</code>
   * @return The reqContext.
   */
  @java.lang.Override
  public ImMessageReply.ReqContext getReqContext() {
    return reqContext_ == null ? ImMessageReply.ReqContext.getDefaultInstance() : reqContext_;
  }
  /**
   * <code>.app.ImMessageReply.ReqContext reqContext = 2;</code>
   */
  @java.lang.Override
  public ImMessageReply.ReqContextOrBuilder getReqContextOrBuilder() {
    return getReqContext();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (imMessage_ != null) {
      output.writeMessage(1, getImMessage());
    }
    if (reqContext_ != null) {
      output.writeMessage(2, getReqContext());
    }
    if (type_ != 0) {
      output.writeInt32(3, type_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (imMessage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getImMessage());
    }
    if (reqContext_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getReqContext());
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, type_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ImMessageReply)) {
      return super.equals(obj);
    }
    ImMessageReply other = (ImMessageReply) obj;

    if (getType()
        != other.getType()) return false;
    if (hasImMessage() != other.hasImMessage()) return false;
    if (hasImMessage()) {
      if (!getImMessage()
          .equals(other.getImMessage())) return false;
    }
    if (hasReqContext() != other.hasReqContext()) return false;
    if (hasReqContext()) {
      if (!getReqContext()
          .equals(other.getReqContext())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    if (hasImMessage()) {
      hash = (37 * hash) + IMMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImMessage().hashCode();
    }
    if (hasReqContext()) {
      hash = (37 * hash) + REQCONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getReqContext().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ImMessageReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ImMessageReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ImMessageReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ImMessageReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ImMessageReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ImMessageReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ImMessageReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ImMessageReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ImMessageReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ImMessageReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ImMessageReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ImMessageReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ImMessageReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code app.ImMessageReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:app.ImMessageReply)
          ImMessageReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMProtoc.internal_static_app_ImMessageReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMProtoc.internal_static_app_ImMessageReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ImMessageReply.class, ImMessageReply.Builder.class);
    }

    // Construct using com.zj.protocol.grpc.ImMessageReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      if (imMessageBuilder_ == null) {
        imMessage_ = null;
      } else {
        imMessage_ = null;
        imMessageBuilder_ = null;
      }
      if (reqContextBuilder_ == null) {
        reqContext_ = null;
      } else {
        reqContext_ = null;
        reqContextBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return IMProtoc.internal_static_app_ImMessageReply_descriptor;
    }

    @java.lang.Override
    public ImMessageReply getDefaultInstanceForType() {
      return ImMessageReply.getDefaultInstance();
    }

    @java.lang.Override
    public ImMessageReply build() {
      ImMessageReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ImMessageReply buildPartial() {
      ImMessageReply result = new ImMessageReply(this);
      result.type_ = type_;
      if (imMessageBuilder_ == null) {
        result.imMessage_ = imMessage_;
      } else {
        result.imMessage_ = imMessageBuilder_.build();
      }
      if (reqContextBuilder_ == null) {
        result.reqContext_ = reqContext_;
      } else {
        result.reqContext_ = reqContextBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ImMessageReply) {
        return mergeFrom((ImMessageReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ImMessageReply other) {
      if (other == ImMessageReply.getDefaultInstance()) return this;
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (other.hasImMessage()) {
        mergeImMessage(other.getImMessage());
      }
      if (other.hasReqContext()) {
        mergeReqContext(other.getReqContext());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ImMessageReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ImMessageReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int type_ ;
    /**
     * <pre>
     **
     * 0 代表是消息 1 代表是服务器收到请求的回执
     * </pre>
     *
     * <code>int32 type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <pre>
     **
     * 0 代表是消息 1 代表是服务器收到请求的回执
     * </pre>
     *
     * <code>int32 type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 0 代表是消息 1 代表是服务器收到请求的回执
     * </pre>
     *
     * <code>int32 type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private ImMessage imMessage_;
    private com.google.protobuf.SingleFieldBuilderV3<ImMessage, ImMessage.Builder, ImMessageOrBuilder> imMessageBuilder_;
    /**
     * <code>.app.ImMessage imMessage = 1;</code>
     * @return Whether the imMessage field is set.
     */
    public boolean hasImMessage() {
      return imMessageBuilder_ != null || imMessage_ != null;
    }
    /**
     * <code>.app.ImMessage imMessage = 1;</code>
     * @return The imMessage.
     */
    public ImMessage getImMessage() {
      if (imMessageBuilder_ == null) {
        return imMessage_ == null ? ImMessage.getDefaultInstance() : imMessage_;
      } else {
        return imMessageBuilder_.getMessage();
      }
    }
    /**
     * <code>.app.ImMessage imMessage = 1;</code>
     */
    public Builder setImMessage(ImMessage value) {
      if (imMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        imMessage_ = value;
        onChanged();
      } else {
        imMessageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.app.ImMessage imMessage = 1;</code>
     */
    public Builder setImMessage(
        ImMessage.Builder builderForValue) {
      if (imMessageBuilder_ == null) {
        imMessage_ = builderForValue.build();
        onChanged();
      } else {
        imMessageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.app.ImMessage imMessage = 1;</code>
     */
    public Builder mergeImMessage(ImMessage value) {
      if (imMessageBuilder_ == null) {
        if (imMessage_ != null) {
          imMessage_ =
            ImMessage.newBuilder(imMessage_).mergeFrom(value).buildPartial();
        } else {
          imMessage_ = value;
        }
        onChanged();
      } else {
        imMessageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.app.ImMessage imMessage = 1;</code>
     */
    public Builder clearImMessage() {
      if (imMessageBuilder_ == null) {
        imMessage_ = null;
        onChanged();
      } else {
        imMessage_ = null;
        imMessageBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.app.ImMessage imMessage = 1;</code>
     */
    public ImMessage.Builder getImMessageBuilder() {
      
      onChanged();
      return getImMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.app.ImMessage imMessage = 1;</code>
     */
    public ImMessageOrBuilder getImMessageOrBuilder() {
      if (imMessageBuilder_ != null) {
        return imMessageBuilder_.getMessageOrBuilder();
      } else {
        return imMessage_ == null ?
            ImMessage.getDefaultInstance() : imMessage_;
      }
    }
    /**
     * <code>.app.ImMessage imMessage = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<ImMessage, ImMessage.Builder, ImMessageOrBuilder>
        getImMessageFieldBuilder() {
      if (imMessageBuilder_ == null) {
        imMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<ImMessage, ImMessage.Builder, ImMessageOrBuilder>(
                getImMessage(),
                getParentForChildren(),
                isClean());
        imMessage_ = null;
      }
      return imMessageBuilder_;
    }

    private ImMessageReply.ReqContext reqContext_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ImMessageReply.ReqContext, ImMessageReply.ReqContext.Builder, ImMessageReply.ReqContextOrBuilder> reqContextBuilder_;
    /**
     * <code>.app.ImMessageReply.ReqContext reqContext = 2;</code>
     * @return Whether the reqContext field is set.
     */
    public boolean hasReqContext() {
      return reqContextBuilder_ != null || reqContext_ != null;
    }
    /**
     * <code>.app.ImMessageReply.ReqContext reqContext = 2;</code>
     * @return The reqContext.
     */
    public ImMessageReply.ReqContext getReqContext() {
      if (reqContextBuilder_ == null) {
        return reqContext_ == null ? ImMessageReply.ReqContext.getDefaultInstance() : reqContext_;
      } else {
        return reqContextBuilder_.getMessage();
      }
    }
    /**
     * <code>.app.ImMessageReply.ReqContext reqContext = 2;</code>
     */
    public Builder setReqContext(ImMessageReply.ReqContext value) {
      if (reqContextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reqContext_ = value;
        onChanged();
      } else {
        reqContextBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.app.ImMessageReply.ReqContext reqContext = 2;</code>
     */
    public Builder setReqContext(
        ImMessageReply.ReqContext.Builder builderForValue) {
      if (reqContextBuilder_ == null) {
        reqContext_ = builderForValue.build();
        onChanged();
      } else {
        reqContextBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.app.ImMessageReply.ReqContext reqContext = 2;</code>
     */
    public Builder mergeReqContext(ImMessageReply.ReqContext value) {
      if (reqContextBuilder_ == null) {
        if (reqContext_ != null) {
          reqContext_ =
            ImMessageReply.ReqContext.newBuilder(reqContext_).mergeFrom(value).buildPartial();
        } else {
          reqContext_ = value;
        }
        onChanged();
      } else {
        reqContextBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.app.ImMessageReply.ReqContext reqContext = 2;</code>
     */
    public Builder clearReqContext() {
      if (reqContextBuilder_ == null) {
        reqContext_ = null;
        onChanged();
      } else {
        reqContext_ = null;
        reqContextBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.app.ImMessageReply.ReqContext reqContext = 2;</code>
     */
    public ImMessageReply.ReqContext.Builder getReqContextBuilder() {
      
      onChanged();
      return getReqContextFieldBuilder().getBuilder();
    }
    /**
     * <code>.app.ImMessageReply.ReqContext reqContext = 2;</code>
     */
    public ImMessageReply.ReqContextOrBuilder getReqContextOrBuilder() {
      if (reqContextBuilder_ != null) {
        return reqContextBuilder_.getMessageOrBuilder();
      } else {
        return reqContext_ == null ?
            ImMessageReply.ReqContext.getDefaultInstance() : reqContext_;
      }
    }
    /**
     * <code>.app.ImMessageReply.ReqContext reqContext = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ImMessageReply.ReqContext, ImMessageReply.ReqContext.Builder, ImMessageReply.ReqContextOrBuilder>
        getReqContextFieldBuilder() {
      if (reqContextBuilder_ == null) {
        reqContextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ImMessageReply.ReqContext, ImMessageReply.ReqContext.Builder, ImMessageReply.ReqContextOrBuilder>(
                getReqContext(),
                getParentForChildren(),
                isClean());
        reqContext_ = null;
      }
      return reqContextBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:app.ImMessageReply)
  }

  // @@protoc_insertion_point(class_scope:app.ImMessageReply)
  private static final ImMessageReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ImMessageReply();
  }

  public static ImMessageReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ImMessageReply>
      PARSER = new com.google.protobuf.AbstractParser<ImMessageReply>() {
    @java.lang.Override
    public ImMessageReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ImMessageReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ImMessageReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ImMessageReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ImMessageReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

