// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

/**
 * Protobuf type {@code app.ImMessage}
 */
public  final class ImMessage extends
    com.google.protobuf.GeneratedMessageLite<
        ImMessage, ImMessage.Builder> implements
    // @@protoc_insertion_point(message_implements:app.ImMessage)
    ImMessageOrBuilder {
  private ImMessage() {
    clientMsgId_ = "";
    msgType_ = "";
  }
  public static final int GROUPID_FIELD_NUMBER = 1;
  private long groupId_;
  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 groupId = 1;</code>
   */
  public long getGroupId() {
    return groupId_;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 groupId = 1;</code>
   */
  private void setGroupId(long value) {
    
    groupId_ = value;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 groupId = 1;</code>
   */
  private void clearGroupId() {
    
    groupId_ = 0L;
  }

  public static final int OWNERID_FIELD_NUMBER = 2;
  private long ownerId_;
  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 ownerId = 2;</code>
   */
  public long getOwnerId() {
    return ownerId_;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 ownerId = 2;</code>
   */
  private void setOwnerId(long value) {
    
    ownerId_ = value;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 ownerId = 2;</code>
   */
  private void clearOwnerId() {
    
    ownerId_ = 0L;
  }

  public static final int SENDTIME_FIELD_NUMBER = 3;
  private long sendTime_;
  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 sendTime = 3;</code>
   */
  public long getSendTime() {
    return sendTime_;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 sendTime = 3;</code>
   */
  private void setSendTime(long value) {
    
    sendTime_ = value;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 sendTime = 3;</code>
   */
  private void clearSendTime() {
    
    sendTime_ = 0L;
  }

  public static final int MSGID_FIELD_NUMBER = 4;
  private long msgId_;
  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 msgId = 4;</code>
   */
  public long getMsgId() {
    return msgId_;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 msgId = 4;</code>
   */
  private void setMsgId(long value) {
    
    msgId_ = value;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>optional uint64 msgId = 4;</code>
   */
  private void clearMsgId() {
    
    msgId_ = 0L;
  }

  public static final int CLIENTMSGID_FIELD_NUMBER = 5;
  private java.lang.String clientMsgId_;
  /**
   * <code>optional string clientMsgId = 5;</code>
   */
  public java.lang.String getClientMsgId() {
    return clientMsgId_;
  }
  /**
   * <code>optional string clientMsgId = 5;</code>
   */
  public com.google.protobuf.ByteString
      getClientMsgIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(clientMsgId_);
  }
  /**
   * <code>optional string clientMsgId = 5;</code>
   */
  private void setClientMsgId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    clientMsgId_ = value;
  }
  /**
   * <code>optional string clientMsgId = 5;</code>
   */
  private void clearClientMsgId() {
    
    clientMsgId_ = getDefaultInstance().getClientMsgId();
  }
  /**
   * <code>optional string clientMsgId = 5;</code>
   */
  private void setClientMsgIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    clientMsgId_ = value.toStringUtf8();
  }

  public static final int MSGTYPE_FIELD_NUMBER = 6;
  private java.lang.String msgType_;
  /**
   * <code>optional string msgType = 6;</code>
   */
  public java.lang.String getMsgType() {
    return msgType_;
  }
  /**
   * <code>optional string msgType = 6;</code>
   */
  public com.google.protobuf.ByteString
      getMsgTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(msgType_);
  }
  /**
   * <code>optional string msgType = 6;</code>
   */
  private void setMsgType(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    msgType_ = value;
  }
  /**
   * <code>optional string msgType = 6;</code>
   */
  private void clearMsgType() {
    
    msgType_ = getDefaultInstance().getMsgType();
  }
  /**
   * <code>optional string msgType = 6;</code>
   */
  private void setMsgTypeBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    msgType_ = value.toStringUtf8();
  }

  public static final int IMGCONTENT_FIELD_NUMBER = 7;
  private ImgContent imgContent_;
  /**
   * <code>optional .app.ImgContent imgContent = 7;</code>
   */
  public boolean hasImgContent() {
    return imgContent_ != null;
  }
  /**
   * <code>optional .app.ImgContent imgContent = 7;</code>
   */
  public ImgContent getImgContent() {
    return imgContent_ == null ? ImgContent.getDefaultInstance() : imgContent_;
  }
  /**
   * <code>optional .app.ImgContent imgContent = 7;</code>
   */
  private void setImgContent(ImgContent value) {
    if (value == null) {
      throw new NullPointerException();
    }
    imgContent_ = value;
    
    }
  /**
   * <code>optional .app.ImgContent imgContent = 7;</code>
   */
  private void setImgContent(
      ImgContent.Builder builderForValue) {
    imgContent_ = builderForValue.build();
    
  }
  /**
   * <code>optional .app.ImgContent imgContent = 7;</code>
   */
  private void mergeImgContent(ImgContent value) {
    if (imgContent_ != null &&
        imgContent_ != ImgContent.getDefaultInstance()) {
      imgContent_ =
        ImgContent.newBuilder(imgContent_).mergeFrom(value).buildPartial();
    } else {
      imgContent_ = value;
    }
    
  }
  /**
   * <code>optional .app.ImgContent imgContent = 7;</code>
   */
  private void clearImgContent() {  imgContent_ = null;
    
  }

  public static final int VIDEOCONTENT_FIELD_NUMBER = 8;
  private VideoContent videoContent_;
  /**
   * <code>optional .app.VideoContent videoContent = 8;</code>
   */
  public boolean hasVideoContent() {
    return videoContent_ != null;
  }
  /**
   * <code>optional .app.VideoContent videoContent = 8;</code>
   */
  public VideoContent getVideoContent() {
    return videoContent_ == null ? VideoContent.getDefaultInstance() : videoContent_;
  }
  /**
   * <code>optional .app.VideoContent videoContent = 8;</code>
   */
  private void setVideoContent(VideoContent value) {
    if (value == null) {
      throw new NullPointerException();
    }
    videoContent_ = value;
    
    }
  /**
   * <code>optional .app.VideoContent videoContent = 8;</code>
   */
  private void setVideoContent(
      VideoContent.Builder builderForValue) {
    videoContent_ = builderForValue.build();
    
  }
  /**
   * <code>optional .app.VideoContent videoContent = 8;</code>
   */
  private void mergeVideoContent(VideoContent value) {
    if (videoContent_ != null &&
        videoContent_ != VideoContent.getDefaultInstance()) {
      videoContent_ =
        VideoContent.newBuilder(videoContent_).mergeFrom(value).buildPartial();
    } else {
      videoContent_ = value;
    }
    
  }
  /**
   * <code>optional .app.VideoContent videoContent = 8;</code>
   */
  private void clearVideoContent() {  videoContent_ = null;
    
  }

  public static final int TEXTCONTENT_FIELD_NUMBER = 9;
  private TextContent textContent_;
  /**
   * <code>optional .app.TextContent textContent = 9;</code>
   */
  public boolean hasTextContent() {
    return textContent_ != null;
  }
  /**
   * <code>optional .app.TextContent textContent = 9;</code>
   */
  public TextContent getTextContent() {
    return textContent_ == null ? TextContent.getDefaultInstance() : textContent_;
  }
  /**
   * <code>optional .app.TextContent textContent = 9;</code>
   */
  private void setTextContent(TextContent value) {
    if (value == null) {
      throw new NullPointerException();
    }
    textContent_ = value;
    
    }
  /**
   * <code>optional .app.TextContent textContent = 9;</code>
   */
  private void setTextContent(
      TextContent.Builder builderForValue) {
    textContent_ = builderForValue.build();
    
  }
  /**
   * <code>optional .app.TextContent textContent = 9;</code>
   */
  private void mergeTextContent(TextContent value) {
    if (textContent_ != null &&
        textContent_ != TextContent.getDefaultInstance()) {
      textContent_ =
        TextContent.newBuilder(textContent_).mergeFrom(value).buildPartial();
    } else {
      textContent_ = value;
    }
    
  }
  /**
   * <code>optional .app.TextContent textContent = 9;</code>
   */
  private void clearTextContent() {  textContent_ = null;
    
  }

  public static final int AUDIOCONTENT_FIELD_NUMBER = 10;
  private AudioContent audioContent_;
  /**
   * <code>optional .app.AudioContent audioContent = 10;</code>
   */
  public boolean hasAudioContent() {
    return audioContent_ != null;
  }
  /**
   * <code>optional .app.AudioContent audioContent = 10;</code>
   */
  public AudioContent getAudioContent() {
    return audioContent_ == null ? AudioContent.getDefaultInstance() : audioContent_;
  }
  /**
   * <code>optional .app.AudioContent audioContent = 10;</code>
   */
  private void setAudioContent(AudioContent value) {
    if (value == null) {
      throw new NullPointerException();
    }
    audioContent_ = value;
    
    }
  /**
   * <code>optional .app.AudioContent audioContent = 10;</code>
   */
  private void setAudioContent(
      AudioContent.Builder builderForValue) {
    audioContent_ = builderForValue.build();
    
  }
  /**
   * <code>optional .app.AudioContent audioContent = 10;</code>
   */
  private void mergeAudioContent(AudioContent value) {
    if (audioContent_ != null &&
        audioContent_ != AudioContent.getDefaultInstance()) {
      audioContent_ =
        AudioContent.newBuilder(audioContent_).mergeFrom(value).buildPartial();
    } else {
      audioContent_ = value;
    }
    
  }
  /**
   * <code>optional .app.AudioContent audioContent = 10;</code>
   */
  private void clearAudioContent() {  audioContent_ = null;
    
  }

  public static final int CCVIDEOCONTENT_FIELD_NUMBER = 11;
  private CCVideoContent ccVideoContent_;
  /**
   * <code>optional .app.CCVideoContent ccVideoContent = 11;</code>
   */
  public boolean hasCcVideoContent() {
    return ccVideoContent_ != null;
  }
  /**
   * <code>optional .app.CCVideoContent ccVideoContent = 11;</code>
   */
  public CCVideoContent getCcVideoContent() {
    return ccVideoContent_ == null ? CCVideoContent.getDefaultInstance() : ccVideoContent_;
  }
  /**
   * <code>optional .app.CCVideoContent ccVideoContent = 11;</code>
   */
  private void setCcVideoContent(CCVideoContent value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ccVideoContent_ = value;
    
    }
  /**
   * <code>optional .app.CCVideoContent ccVideoContent = 11;</code>
   */
  private void setCcVideoContent(
      CCVideoContent.Builder builderForValue) {
    ccVideoContent_ = builderForValue.build();
    
  }
  /**
   * <code>optional .app.CCVideoContent ccVideoContent = 11;</code>
   */
  private void mergeCcVideoContent(CCVideoContent value) {
    if (ccVideoContent_ != null &&
        ccVideoContent_ != CCVideoContent.getDefaultInstance()) {
      ccVideoContent_ =
        CCVideoContent.newBuilder(ccVideoContent_).mergeFrom(value).buildPartial();
    } else {
      ccVideoContent_ = value;
    }
    
  }
  /**
   * <code>optional .app.CCVideoContent ccVideoContent = 11;</code>
   */
  private void clearCcVideoContent() {  ccVideoContent_ = null;
    
  }

  public static final int QUESTIONCONTENT_FIELD_NUMBER = 12;
  private QuestionContent questionContent_;
  /**
   * <code>optional .app.QuestionContent questionContent = 12;</code>
   */
  public boolean hasQuestionContent() {
    return questionContent_ != null;
  }
  /**
   * <code>optional .app.QuestionContent questionContent = 12;</code>
   */
  public QuestionContent getQuestionContent() {
    return questionContent_ == null ? QuestionContent.getDefaultInstance() : questionContent_;
  }
  /**
   * <code>optional .app.QuestionContent questionContent = 12;</code>
   */
  private void setQuestionContent(QuestionContent value) {
    if (value == null) {
      throw new NullPointerException();
    }
    questionContent_ = value;
    
    }
  /**
   * <code>optional .app.QuestionContent questionContent = 12;</code>
   */
  private void setQuestionContent(
      QuestionContent.Builder builderForValue) {
    questionContent_ = builderForValue.build();
    
  }
  /**
   * <code>optional .app.QuestionContent questionContent = 12;</code>
   */
  private void mergeQuestionContent(QuestionContent value) {
    if (questionContent_ != null &&
        questionContent_ != QuestionContent.getDefaultInstance()) {
      questionContent_ =
        QuestionContent.newBuilder(questionContent_).mergeFrom(value).buildPartial();
    } else {
      questionContent_ = value;
    }
    
  }
  /**
   * <code>optional .app.QuestionContent questionContent = 12;</code>
   */
  private void clearQuestionContent() {  questionContent_ = null;
    
  }

  public static final int SENDER_FIELD_NUMBER = 13;
  private SenderInfo sender_;
  /**
   * <code>optional .app.SenderInfo sender = 13;</code>
   */
  public boolean hasSender() {
    return sender_ != null;
  }
  /**
   * <code>optional .app.SenderInfo sender = 13;</code>
   */
  public SenderInfo getSender() {
    return sender_ == null ? SenderInfo.getDefaultInstance() : sender_;
  }
  /**
   * <code>optional .app.SenderInfo sender = 13;</code>
   */
  private void setSender(SenderInfo value) {
    if (value == null) {
      throw new NullPointerException();
    }
    sender_ = value;
    
    }
  /**
   * <code>optional .app.SenderInfo sender = 13;</code>
   */
  private void setSender(
      SenderInfo.Builder builderForValue) {
    sender_ = builderForValue.build();
    
  }
  /**
   * <code>optional .app.SenderInfo sender = 13;</code>
   */
  private void mergeSender(SenderInfo value) {
    if (sender_ != null &&
        sender_ != SenderInfo.getDefaultInstance()) {
      sender_ =
        SenderInfo.newBuilder(sender_).mergeFrom(value).buildPartial();
    } else {
      sender_ = value;
    }
    
  }
  /**
   * <code>optional .app.SenderInfo sender = 13;</code>
   */
  private void clearSender() {  sender_ = null;
    
  }

  public static final int REPLYMSGID_FIELD_NUMBER = 14;
  private long replyMsgId_;
  /**
   * <code>optional uint64 replyMsgId = 14;</code>
   */
  public long getReplyMsgId() {
    return replyMsgId_;
  }
  /**
   * <code>optional uint64 replyMsgId = 14;</code>
   */
  private void setReplyMsgId(long value) {
    
    replyMsgId_ = value;
  }
  /**
   * <code>optional uint64 replyMsgId = 14;</code>
   */
  private void clearReplyMsgId() {
    
    replyMsgId_ = 0L;
  }

  public static final int REPLYMSG_FIELD_NUMBER = 15;
  private ImMessage replyMsg_;
  /**
   * <code>optional .app.ImMessage replyMsg = 15;</code>
   */
  public boolean hasReplyMsg() {
    return replyMsg_ != null;
  }
  /**
   * <code>optional .app.ImMessage replyMsg = 15;</code>
   */
  public ImMessage getReplyMsg() {
    return replyMsg_ == null ? ImMessage.getDefaultInstance() : replyMsg_;
  }
  /**
   * <code>optional .app.ImMessage replyMsg = 15;</code>
   */
  private void setReplyMsg(ImMessage value) {
    if (value == null) {
      throw new NullPointerException();
    }
    replyMsg_ = value;
    
    }
  /**
   * <code>optional .app.ImMessage replyMsg = 15;</code>
   */
  private void setReplyMsg(
      ImMessage.Builder builderForValue) {
    replyMsg_ = builderForValue.build();
    
  }
  /**
   * <code>optional .app.ImMessage replyMsg = 15;</code>
   */
  private void mergeReplyMsg(ImMessage value) {
    if (replyMsg_ != null &&
        replyMsg_ != ImMessage.getDefaultInstance()) {
      replyMsg_ =
        ImMessage.newBuilder(replyMsg_).mergeFrom(value).buildPartial();
    } else {
      replyMsg_ = value;
    }
    
  }
  /**
   * <code>optional .app.ImMessage replyMsg = 15;</code>
   */
  private void clearReplyMsg() {  replyMsg_ = null;
    
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (groupId_ != 0L) {
      output.writeUInt64(1, groupId_);
    }
    if (ownerId_ != 0L) {
      output.writeUInt64(2, ownerId_);
    }
    if (sendTime_ != 0L) {
      output.writeUInt64(3, sendTime_);
    }
    if (msgId_ != 0L) {
      output.writeUInt64(4, msgId_);
    }
    if (!clientMsgId_.isEmpty()) {
      output.writeString(5, getClientMsgId());
    }
    if (!msgType_.isEmpty()) {
      output.writeString(6, getMsgType());
    }
    if (imgContent_ != null) {
      output.writeMessage(7, getImgContent());
    }
    if (videoContent_ != null) {
      output.writeMessage(8, getVideoContent());
    }
    if (textContent_ != null) {
      output.writeMessage(9, getTextContent());
    }
    if (audioContent_ != null) {
      output.writeMessage(10, getAudioContent());
    }
    if (ccVideoContent_ != null) {
      output.writeMessage(11, getCcVideoContent());
    }
    if (questionContent_ != null) {
      output.writeMessage(12, getQuestionContent());
    }
    if (sender_ != null) {
      output.writeMessage(13, getSender());
    }
    if (replyMsgId_ != 0L) {
      output.writeUInt64(14, replyMsgId_);
    }
    if (replyMsg_ != null) {
      output.writeMessage(15, getReplyMsg());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (groupId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, groupId_);
    }
    if (ownerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, ownerId_);
    }
    if (sendTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, sendTime_);
    }
    if (msgId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, msgId_);
    }
    if (!clientMsgId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(5, getClientMsgId());
    }
    if (!msgType_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(6, getMsgType());
    }
    if (imgContent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getImgContent());
    }
    if (videoContent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getVideoContent());
    }
    if (textContent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getTextContent());
    }
    if (audioContent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getAudioContent());
    }
    if (ccVideoContent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getCcVideoContent());
    }
    if (questionContent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getQuestionContent());
    }
    if (sender_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getSender());
    }
    if (replyMsgId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(14, replyMsgId_);
    }
    if (replyMsg_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, getReplyMsg());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static ImMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ImMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ImMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ImMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ImMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ImMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ImMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ImMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ImMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ImMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ImMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code app.ImMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<ImMessage, Builder> implements
      // @@protoc_insertion_point(builder_implements:app.ImMessage)
          ImMessageOrBuilder {
    // Construct using com.zj.protocol.grpc.ImMessage.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * </pre>
     *
     * <code>optional uint64 groupId = 1;</code>
     */
    public long getGroupId() {
      return instance.getGroupId();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional uint64 groupId = 1;</code>
     */
    public Builder setGroupId(long value) {
      copyOnWrite();
      instance.setGroupId(value);
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional uint64 groupId = 1;</code>
     */
    public Builder clearGroupId() {
      copyOnWrite();
      instance.clearGroupId();
      return this;
    }

    /**
     * <pre>
     * </pre>
     *
     * <code>optional uint64 ownerId = 2;</code>
     */
    public long getOwnerId() {
      return instance.getOwnerId();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional uint64 ownerId = 2;</code>
     */
    public Builder setOwnerId(long value) {
      copyOnWrite();
      instance.setOwnerId(value);
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional uint64 ownerId = 2;</code>
     */
    public Builder clearOwnerId() {
      copyOnWrite();
      instance.clearOwnerId();
      return this;
    }

    /**
     * <pre>
     * </pre>
     *
     * <code>optional uint64 sendTime = 3;</code>
     */
    public long getSendTime() {
      return instance.getSendTime();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional uint64 sendTime = 3;</code>
     */
    public Builder setSendTime(long value) {
      copyOnWrite();
      instance.setSendTime(value);
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional uint64 sendTime = 3;</code>
     */
    public Builder clearSendTime() {
      copyOnWrite();
      instance.clearSendTime();
      return this;
    }

    /**
     * <pre>
     * </pre>
     *
     * <code>optional uint64 msgId = 4;</code>
     */
    public long getMsgId() {
      return instance.getMsgId();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional uint64 msgId = 4;</code>
     */
    public Builder setMsgId(long value) {
      copyOnWrite();
      instance.setMsgId(value);
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>optional uint64 msgId = 4;</code>
     */
    public Builder clearMsgId() {
      copyOnWrite();
      instance.clearMsgId();
      return this;
    }

    /**
     * <code>optional string clientMsgId = 5;</code>
     */
    public java.lang.String getClientMsgId() {
      return instance.getClientMsgId();
    }
    /**
     * <code>optional string clientMsgId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getClientMsgIdBytes() {
      return instance.getClientMsgIdBytes();
    }
    /**
     * <code>optional string clientMsgId = 5;</code>
     */
    public Builder setClientMsgId(
        java.lang.String value) {
      copyOnWrite();
      instance.setClientMsgId(value);
      return this;
    }
    /**
     * <code>optional string clientMsgId = 5;</code>
     */
    public Builder clearClientMsgId() {
      copyOnWrite();
      instance.clearClientMsgId();
      return this;
    }
    /**
     * <code>optional string clientMsgId = 5;</code>
     */
    public Builder setClientMsgIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setClientMsgIdBytes(value);
      return this;
    }

    /**
     * <code>optional string msgType = 6;</code>
     */
    public java.lang.String getMsgType() {
      return instance.getMsgType();
    }
    /**
     * <code>optional string msgType = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMsgTypeBytes() {
      return instance.getMsgTypeBytes();
    }
    /**
     * <code>optional string msgType = 6;</code>
     */
    public Builder setMsgType(
        java.lang.String value) {
      copyOnWrite();
      instance.setMsgType(value);
      return this;
    }
    /**
     * <code>optional string msgType = 6;</code>
     */
    public Builder clearMsgType() {
      copyOnWrite();
      instance.clearMsgType();
      return this;
    }
    /**
     * <code>optional string msgType = 6;</code>
     */
    public Builder setMsgTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMsgTypeBytes(value);
      return this;
    }

    /**
     * <code>optional .app.ImgContent imgContent = 7;</code>
     */
    public boolean hasImgContent() {
      return instance.hasImgContent();
    }
    /**
     * <code>optional .app.ImgContent imgContent = 7;</code>
     */
    public ImgContent getImgContent() {
      return instance.getImgContent();
    }
    /**
     * <code>optional .app.ImgContent imgContent = 7;</code>
     */
    public Builder setImgContent(ImgContent value) {
      copyOnWrite();
      instance.setImgContent(value);
      return this;
      }
    /**
     * <code>optional .app.ImgContent imgContent = 7;</code>
     */
    public Builder setImgContent(
        ImgContent.Builder builderForValue) {
      copyOnWrite();
      instance.setImgContent(builderForValue);
      return this;
    }
    /**
     * <code>optional .app.ImgContent imgContent = 7;</code>
     */
    public Builder mergeImgContent(ImgContent value) {
      copyOnWrite();
      instance.mergeImgContent(value);
      return this;
    }
    /**
     * <code>optional .app.ImgContent imgContent = 7;</code>
     */
    public Builder clearImgContent() {  copyOnWrite();
      instance.clearImgContent();
      return this;
    }

    /**
     * <code>optional .app.VideoContent videoContent = 8;</code>
     */
    public boolean hasVideoContent() {
      return instance.hasVideoContent();
    }
    /**
     * <code>optional .app.VideoContent videoContent = 8;</code>
     */
    public VideoContent getVideoContent() {
      return instance.getVideoContent();
    }
    /**
     * <code>optional .app.VideoContent videoContent = 8;</code>
     */
    public Builder setVideoContent(VideoContent value) {
      copyOnWrite();
      instance.setVideoContent(value);
      return this;
      }
    /**
     * <code>optional .app.VideoContent videoContent = 8;</code>
     */
    public Builder setVideoContent(
        VideoContent.Builder builderForValue) {
      copyOnWrite();
      instance.setVideoContent(builderForValue);
      return this;
    }
    /**
     * <code>optional .app.VideoContent videoContent = 8;</code>
     */
    public Builder mergeVideoContent(VideoContent value) {
      copyOnWrite();
      instance.mergeVideoContent(value);
      return this;
    }
    /**
     * <code>optional .app.VideoContent videoContent = 8;</code>
     */
    public Builder clearVideoContent() {  copyOnWrite();
      instance.clearVideoContent();
      return this;
    }

    /**
     * <code>optional .app.TextContent textContent = 9;</code>
     */
    public boolean hasTextContent() {
      return instance.hasTextContent();
    }
    /**
     * <code>optional .app.TextContent textContent = 9;</code>
     */
    public TextContent getTextContent() {
      return instance.getTextContent();
    }
    /**
     * <code>optional .app.TextContent textContent = 9;</code>
     */
    public Builder setTextContent(TextContent value) {
      copyOnWrite();
      instance.setTextContent(value);
      return this;
      }
    /**
     * <code>optional .app.TextContent textContent = 9;</code>
     */
    public Builder setTextContent(
        TextContent.Builder builderForValue) {
      copyOnWrite();
      instance.setTextContent(builderForValue);
      return this;
    }
    /**
     * <code>optional .app.TextContent textContent = 9;</code>
     */
    public Builder mergeTextContent(TextContent value) {
      copyOnWrite();
      instance.mergeTextContent(value);
      return this;
    }
    /**
     * <code>optional .app.TextContent textContent = 9;</code>
     */
    public Builder clearTextContent() {  copyOnWrite();
      instance.clearTextContent();
      return this;
    }

    /**
     * <code>optional .app.AudioContent audioContent = 10;</code>
     */
    public boolean hasAudioContent() {
      return instance.hasAudioContent();
    }
    /**
     * <code>optional .app.AudioContent audioContent = 10;</code>
     */
    public AudioContent getAudioContent() {
      return instance.getAudioContent();
    }
    /**
     * <code>optional .app.AudioContent audioContent = 10;</code>
     */
    public Builder setAudioContent(AudioContent value) {
      copyOnWrite();
      instance.setAudioContent(value);
      return this;
      }
    /**
     * <code>optional .app.AudioContent audioContent = 10;</code>
     */
    public Builder setAudioContent(
        AudioContent.Builder builderForValue) {
      copyOnWrite();
      instance.setAudioContent(builderForValue);
      return this;
    }
    /**
     * <code>optional .app.AudioContent audioContent = 10;</code>
     */
    public Builder mergeAudioContent(AudioContent value) {
      copyOnWrite();
      instance.mergeAudioContent(value);
      return this;
    }
    /**
     * <code>optional .app.AudioContent audioContent = 10;</code>
     */
    public Builder clearAudioContent() {  copyOnWrite();
      instance.clearAudioContent();
      return this;
    }

    /**
     * <code>optional .app.CCVideoContent ccVideoContent = 11;</code>
     */
    public boolean hasCcVideoContent() {
      return instance.hasCcVideoContent();
    }
    /**
     * <code>optional .app.CCVideoContent ccVideoContent = 11;</code>
     */
    public CCVideoContent getCcVideoContent() {
      return instance.getCcVideoContent();
    }
    /**
     * <code>optional .app.CCVideoContent ccVideoContent = 11;</code>
     */
    public Builder setCcVideoContent(CCVideoContent value) {
      copyOnWrite();
      instance.setCcVideoContent(value);
      return this;
      }
    /**
     * <code>optional .app.CCVideoContent ccVideoContent = 11;</code>
     */
    public Builder setCcVideoContent(
        CCVideoContent.Builder builderForValue) {
      copyOnWrite();
      instance.setCcVideoContent(builderForValue);
      return this;
    }
    /**
     * <code>optional .app.CCVideoContent ccVideoContent = 11;</code>
     */
    public Builder mergeCcVideoContent(CCVideoContent value) {
      copyOnWrite();
      instance.mergeCcVideoContent(value);
      return this;
    }
    /**
     * <code>optional .app.CCVideoContent ccVideoContent = 11;</code>
     */
    public Builder clearCcVideoContent() {  copyOnWrite();
      instance.clearCcVideoContent();
      return this;
    }

    /**
     * <code>optional .app.QuestionContent questionContent = 12;</code>
     */
    public boolean hasQuestionContent() {
      return instance.hasQuestionContent();
    }
    /**
     * <code>optional .app.QuestionContent questionContent = 12;</code>
     */
    public QuestionContent getQuestionContent() {
      return instance.getQuestionContent();
    }
    /**
     * <code>optional .app.QuestionContent questionContent = 12;</code>
     */
    public Builder setQuestionContent(QuestionContent value) {
      copyOnWrite();
      instance.setQuestionContent(value);
      return this;
      }
    /**
     * <code>optional .app.QuestionContent questionContent = 12;</code>
     */
    public Builder setQuestionContent(
        QuestionContent.Builder builderForValue) {
      copyOnWrite();
      instance.setQuestionContent(builderForValue);
      return this;
    }
    /**
     * <code>optional .app.QuestionContent questionContent = 12;</code>
     */
    public Builder mergeQuestionContent(QuestionContent value) {
      copyOnWrite();
      instance.mergeQuestionContent(value);
      return this;
    }
    /**
     * <code>optional .app.QuestionContent questionContent = 12;</code>
     */
    public Builder clearQuestionContent() {  copyOnWrite();
      instance.clearQuestionContent();
      return this;
    }

    /**
     * <code>optional .app.SenderInfo sender = 13;</code>
     */
    public boolean hasSender() {
      return instance.hasSender();
    }
    /**
     * <code>optional .app.SenderInfo sender = 13;</code>
     */
    public SenderInfo getSender() {
      return instance.getSender();
    }
    /**
     * <code>optional .app.SenderInfo sender = 13;</code>
     */
    public Builder setSender(SenderInfo value) {
      copyOnWrite();
      instance.setSender(value);
      return this;
      }
    /**
     * <code>optional .app.SenderInfo sender = 13;</code>
     */
    public Builder setSender(
        SenderInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setSender(builderForValue);
      return this;
    }
    /**
     * <code>optional .app.SenderInfo sender = 13;</code>
     */
    public Builder mergeSender(SenderInfo value) {
      copyOnWrite();
      instance.mergeSender(value);
      return this;
    }
    /**
     * <code>optional .app.SenderInfo sender = 13;</code>
     */
    public Builder clearSender() {  copyOnWrite();
      instance.clearSender();
      return this;
    }

    /**
     * <code>optional uint64 replyMsgId = 14;</code>
     */
    public long getReplyMsgId() {
      return instance.getReplyMsgId();
    }
    /**
     * <code>optional uint64 replyMsgId = 14;</code>
     */
    public Builder setReplyMsgId(long value) {
      copyOnWrite();
      instance.setReplyMsgId(value);
      return this;
    }
    /**
     * <code>optional uint64 replyMsgId = 14;</code>
     */
    public Builder clearReplyMsgId() {
      copyOnWrite();
      instance.clearReplyMsgId();
      return this;
    }

    /**
     * <code>optional .app.ImMessage replyMsg = 15;</code>
     */
    public boolean hasReplyMsg() {
      return instance.hasReplyMsg();
    }
    /**
     * <code>optional .app.ImMessage replyMsg = 15;</code>
     */
    public ImMessage getReplyMsg() {
      return instance.getReplyMsg();
    }
    /**
     * <code>optional .app.ImMessage replyMsg = 15;</code>
     */
    public Builder setReplyMsg(ImMessage value) {
      copyOnWrite();
      instance.setReplyMsg(value);
      return this;
      }
    /**
     * <code>optional .app.ImMessage replyMsg = 15;</code>
     */
    public Builder setReplyMsg(
        ImMessage.Builder builderForValue) {
      copyOnWrite();
      instance.setReplyMsg(builderForValue);
      return this;
    }
    /**
     * <code>optional .app.ImMessage replyMsg = 15;</code>
     */
    public Builder mergeReplyMsg(ImMessage value) {
      copyOnWrite();
      instance.mergeReplyMsg(value);
      return this;
    }
    /**
     * <code>optional .app.ImMessage replyMsg = 15;</code>
     */
    public Builder clearReplyMsg() {  copyOnWrite();
      instance.clearReplyMsg();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:app.ImMessage)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ImMessage();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        ImMessage other = (ImMessage) arg1;
        groupId_ = visitor.visitLong(groupId_ != 0L, groupId_,
            other.groupId_ != 0L, other.groupId_);
        ownerId_ = visitor.visitLong(ownerId_ != 0L, ownerId_,
            other.ownerId_ != 0L, other.ownerId_);
        sendTime_ = visitor.visitLong(sendTime_ != 0L, sendTime_,
            other.sendTime_ != 0L, other.sendTime_);
        msgId_ = visitor.visitLong(msgId_ != 0L, msgId_,
            other.msgId_ != 0L, other.msgId_);
        clientMsgId_ = visitor.visitString(!clientMsgId_.isEmpty(), clientMsgId_,
            !other.clientMsgId_.isEmpty(), other.clientMsgId_);
        msgType_ = visitor.visitString(!msgType_.isEmpty(), msgType_,
            !other.msgType_.isEmpty(), other.msgType_);
        imgContent_ = visitor.visitMessage(imgContent_, other.imgContent_);
        videoContent_ = visitor.visitMessage(videoContent_, other.videoContent_);
        textContent_ = visitor.visitMessage(textContent_, other.textContent_);
        audioContent_ = visitor.visitMessage(audioContent_, other.audioContent_);
        ccVideoContent_ = visitor.visitMessage(ccVideoContent_, other.ccVideoContent_);
        questionContent_ = visitor.visitMessage(questionContent_, other.questionContent_);
        sender_ = visitor.visitMessage(sender_, other.sender_);
        replyMsgId_ = visitor.visitLong(replyMsgId_ != 0L, replyMsgId_,
            other.replyMsgId_ != 0L, other.replyMsgId_);
        replyMsg_ = visitor.visitMessage(replyMsg_, other.replyMsg_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                groupId_ = input.readUInt64();
                break;
              }
              case 16: {

                ownerId_ = input.readUInt64();
                break;
              }
              case 24: {

                sendTime_ = input.readUInt64();
                break;
              }
              case 32: {

                msgId_ = input.readUInt64();
                break;
              }
              case 42: {
                String s = input.readStringRequireUtf8();

                clientMsgId_ = s;
                break;
              }
              case 50: {
                String s = input.readStringRequireUtf8();

                msgType_ = s;
                break;
              }
              case 58: {
                ImgContent.Builder subBuilder = null;
                if (imgContent_ != null) {
                  subBuilder = imgContent_.toBuilder();
                }
                imgContent_ = input.readMessage(ImgContent.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(imgContent_);
                  imgContent_ = subBuilder.buildPartial();
                }

                break;
              }
              case 66: {
                VideoContent.Builder subBuilder = null;
                if (videoContent_ != null) {
                  subBuilder = videoContent_.toBuilder();
                }
                videoContent_ = input.readMessage(VideoContent.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(videoContent_);
                  videoContent_ = subBuilder.buildPartial();
                }

                break;
              }
              case 74: {
                TextContent.Builder subBuilder = null;
                if (textContent_ != null) {
                  subBuilder = textContent_.toBuilder();
                }
                textContent_ = input.readMessage(TextContent.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(textContent_);
                  textContent_ = subBuilder.buildPartial();
                }

                break;
              }
              case 82: {
                AudioContent.Builder subBuilder = null;
                if (audioContent_ != null) {
                  subBuilder = audioContent_.toBuilder();
                }
                audioContent_ = input.readMessage(AudioContent.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(audioContent_);
                  audioContent_ = subBuilder.buildPartial();
                }

                break;
              }
              case 90: {
                CCVideoContent.Builder subBuilder = null;
                if (ccVideoContent_ != null) {
                  subBuilder = ccVideoContent_.toBuilder();
                }
                ccVideoContent_ = input.readMessage(CCVideoContent.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(ccVideoContent_);
                  ccVideoContent_ = subBuilder.buildPartial();
                }

                break;
              }
              case 98: {
                QuestionContent.Builder subBuilder = null;
                if (questionContent_ != null) {
                  subBuilder = questionContent_.toBuilder();
                }
                questionContent_ = input.readMessage(QuestionContent.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(questionContent_);
                  questionContent_ = subBuilder.buildPartial();
                }

                break;
              }
              case 106: {
                SenderInfo.Builder subBuilder = null;
                if (sender_ != null) {
                  subBuilder = sender_.toBuilder();
                }
                sender_ = input.readMessage(SenderInfo.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(sender_);
                  sender_ = subBuilder.buildPartial();
                }

                break;
              }
              case 112: {

                replyMsgId_ = input.readUInt64();
                break;
              }
              case 122: {
                ImMessage.Builder subBuilder = null;
                if (replyMsg_ != null) {
                  subBuilder = replyMsg_.toBuilder();
                }
                replyMsg_ = input.readMessage(ImMessage.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(replyMsg_);
                  replyMsg_ = subBuilder.buildPartial();
                }

                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (ImMessage.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:app.ImMessage)
  private static final ImMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ImMessage();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static ImMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ImMessage> PARSER;

  public static com.google.protobuf.Parser<ImMessage> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

