// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

public interface ListenTopicReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:app.ListenTopicReply)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   *具体的topic key
   * </pre>
   *
   * <code>optional string topic = 1;</code>
   */
  java.lang.String getTopic();
  /**
   * <pre>
   *具体的topic key
   * </pre>
   *
   * <code>optional string topic = 1;</code>
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <pre>
   *由业务推送过来的json信息，根据业务不同内部的格式不同
   * </pre>
   *
   * <code>optional string data = 2;</code>
   */
  java.lang.String getData();
  /**
   * <pre>
   *由业务推送过来的json信息，根据业务不同内部的格式不同
   * </pre>
   *
   * <code>optional string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
