// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

/**
 * Protobuf type {@code app.ListenTopicReq}
 */
public  final class ListenTopicReq extends
    com.google.protobuf.GeneratedMessageLite<
        ListenTopicReq, ListenTopicReq.Builder> implements
    // @@protoc_insertion_point(message_implements:app.ListenTopicReq)
    ListenTopicReqOrBuilder {
  private ListenTopicReq() {
    topic_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * Protobuf enum {@code app.ListenTopicReq.Method}
   */
  public enum Method
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Subscribe = 0;</code>
     */
    Subscribe(0),
    /**
     * <code>UnSubscribe = 1;</code>
     */
    UnSubscribe(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Subscribe = 0;</code>
     */
    public static final int Subscribe_VALUE = 0;
    /**
     * <code>UnSubscribe = 1;</code>
     */
    public static final int UnSubscribe_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Method valueOf(int value) {
      return forNumber(value);
    }

    public static Method forNumber(int value) {
      switch (value) {
        case 0: return Subscribe;
        case 1: return UnSubscribe;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Method>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Method> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Method>() {
            public Method findValueByNumber(int number) {
              return Method.forNumber(number);
            }
          };

    private final int value;

    private Method(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:app.ListenTopicReq.Method)
  }

  private int bitField0_;
  public static final int TOPIC_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<String> topic_;
  /**
   * <pre>
   *具体的topic key ，可多值
   * </pre>
   *
   * <code>repeated string topic = 1;</code>
   */
  public java.util.List<String> getTopicList() {
    return topic_;
  }
  /**
   * <pre>
   *具体的topic key ，可多值
   * </pre>
   *
   * <code>repeated string topic = 1;</code>
   */
  public int getTopicCount() {
    return topic_.size();
  }
  /**
   * <pre>
   *具体的topic key ，可多值
   * </pre>
   *
   * <code>repeated string topic = 1;</code>
   */
  public java.lang.String getTopic(int index) {
    return topic_.get(index);
  }
  /**
   * <pre>
   *具体的topic key ，可多值
   * </pre>
   *
   * <code>repeated string topic = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTopicBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        topic_.get(index));
  }
  private void ensureTopicIsMutable() {
    if (!topic_.isModifiable()) {
      topic_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(topic_);
     }
  }
  /**
   * <pre>
   *具体的topic key ，可多值
   * </pre>
   *
   * <code>repeated string topic = 1;</code>
   */
  private void setTopic(
      int index, java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureTopicIsMutable();
    topic_.set(index, value);
  }
  /**
   * <pre>
   *具体的topic key ，可多值
   * </pre>
   *
   * <code>repeated string topic = 1;</code>
   */
  private void addTopic(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureTopicIsMutable();
    topic_.add(value);
  }
  /**
   * <pre>
   *具体的topic key ，可多值
   * </pre>
   *
   * <code>repeated string topic = 1;</code>
   */
  private void addAllTopic(
      java.lang.Iterable<java.lang.String> values) {
    ensureTopicIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, topic_);
  }
  /**
   * <pre>
   *具体的topic key ，可多值
   * </pre>
   *
   * <code>repeated string topic = 1;</code>
   */
  private void clearTopic() {
    topic_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   *具体的topic key ，可多值
   * </pre>
   *
   * <code>repeated string topic = 1;</code>
   */
  private void addTopicBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    ensureTopicIsMutable();
    topic_.add(value.toStringUtf8());
  }

  public static final int METHOD_FIELD_NUMBER = 2;
  private int method_;
  /**
   * <code>optional .app.ListenTopicReq.Method method = 2;</code>
   */
  public int getMethodValue() {
    return method_;
  }
  /**
   * <code>optional .app.ListenTopicReq.Method method = 2;</code>
   */
  public ListenTopicReq.Method getMethod() {
    ListenTopicReq.Method result = ListenTopicReq.Method.forNumber(method_);
    return result == null ? ListenTopicReq.Method.UNRECOGNIZED : result;
  }
  /**
   * <code>optional .app.ListenTopicReq.Method method = 2;</code>
   */
  private void setMethodValue(int value) {
      method_ = value;
  }
  /**
   * <code>optional .app.ListenTopicReq.Method method = 2;</code>
   */
  private void setMethod(ListenTopicReq.Method value) {
    if (value == null) {
      throw new NullPointerException();
    }
    
    method_ = value.getNumber();
  }
  /**
   * <code>optional .app.ListenTopicReq.Method method = 2;</code>
   */
  private void clearMethod() {
    
    method_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < topic_.size(); i++) {
      output.writeString(1, topic_.get(i));
    }
    if (method_ != ListenTopicReq.Method.Subscribe.getNumber()) {
      output.writeEnum(2, method_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < topic_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeStringSizeNoTag(topic_.get(i));
      }
      size += dataSize;
      size += 1 * getTopicList().size();
    }
    if (method_ != ListenTopicReq.Method.Subscribe.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, method_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static ListenTopicReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ListenTopicReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ListenTopicReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ListenTopicReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ListenTopicReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ListenTopicReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ListenTopicReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ListenTopicReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ListenTopicReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ListenTopicReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ListenTopicReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code app.ListenTopicReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<ListenTopicReq, Builder> implements
      // @@protoc_insertion_point(builder_implements:app.ListenTopicReq)
          ListenTopicReqOrBuilder {
    // Construct using com.zj.protocol.grpc.ListenTopicReq.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     *具体的topic key ，可多值
     * </pre>
     *
     * <code>repeated string topic = 1;</code>
     */
    public java.util.List<String>
        getTopicList() {
      return java.util.Collections.unmodifiableList(
          instance.getTopicList());
    }
    /**
     * <pre>
     *具体的topic key ，可多值
     * </pre>
     *
     * <code>repeated string topic = 1;</code>
     */
    public int getTopicCount() {
      return instance.getTopicCount();
    }
    /**
     * <pre>
     *具体的topic key ，可多值
     * </pre>
     *
     * <code>repeated string topic = 1;</code>
     */
    public java.lang.String getTopic(int index) {
      return instance.getTopic(index);
    }
    /**
     * <pre>
     *具体的topic key ，可多值
     * </pre>
     *
     * <code>repeated string topic = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes(int index) {
      return instance.getTopicBytes(index);
    }
    /**
     * <pre>
     *具体的topic key ，可多值
     * </pre>
     *
     * <code>repeated string topic = 1;</code>
     */
    public Builder setTopic(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setTopic(index, value);
      return this;
    }
    /**
     * <pre>
     *具体的topic key ，可多值
     * </pre>
     *
     * <code>repeated string topic = 1;</code>
     */
    public Builder addTopic(
        java.lang.String value) {
      copyOnWrite();
      instance.addTopic(value);
      return this;
    }
    /**
     * <pre>
     *具体的topic key ，可多值
     * </pre>
     *
     * <code>repeated string topic = 1;</code>
     */
    public Builder addAllTopic(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllTopic(values);
      return this;
    }
    /**
     * <pre>
     *具体的topic key ，可多值
     * </pre>
     *
     * <code>repeated string topic = 1;</code>
     */
    public Builder clearTopic() {
      copyOnWrite();
      instance.clearTopic();
      return this;
    }
    /**
     * <pre>
     *具体的topic key ，可多值
     * </pre>
     *
     * <code>repeated string topic = 1;</code>
     */
    public Builder addTopicBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addTopicBytes(value);
      return this;
    }

    /**
     * <code>optional .app.ListenTopicReq.Method method = 2;</code>
     */
    public int getMethodValue() {
      return instance.getMethodValue();
    }
    /**
     * <code>optional .app.ListenTopicReq.Method method = 2;</code>
     */
    public Builder setMethodValue(int value) {
      copyOnWrite();
      instance.setMethodValue(value);
      return this;
    }
    /**
     * <code>optional .app.ListenTopicReq.Method method = 2;</code>
     */
    public ListenTopicReq.Method getMethod() {
      return instance.getMethod();
    }
    /**
     * <code>optional .app.ListenTopicReq.Method method = 2;</code>
     */
    public Builder setMethod(ListenTopicReq.Method value) {
      copyOnWrite();
      instance.setMethod(value);
      return this;
    }
    /**
     * <code>optional .app.ListenTopicReq.Method method = 2;</code>
     */
    public Builder clearMethod() {
      copyOnWrite();
      instance.clearMethod();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:app.ListenTopicReq)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ListenTopicReq();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        topic_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        ListenTopicReq other = (ListenTopicReq) arg1;
        topic_= visitor.visitList(topic_, other.topic_);
        method_ = visitor.visitInt(method_ != 0, method_,    other.method_ != 0, other.method_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();
                if (!topic_.isModifiable()) {
                  topic_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(topic_);
                }
                topic_.add(s);
                break;
              }
              case 16: {
                int rawValue = input.readEnum();

                method_ = rawValue;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (ListenTopicReq.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:app.ListenTopicReq)
  private static final ListenTopicReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ListenTopicReq();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static ListenTopicReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListenTopicReq> PARSER;

  public static com.google.protobuf.Parser<ListenTopicReq> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

