// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

public interface ListenTopicReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:app.ListenTopicReq)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   *具体的topic key ，可多值
   * </pre>
   *
   * <code>repeated string topic = 1;</code>
   */
  java.util.List<String>
      getTopicList();
  /**
   * <pre>
   *具体的topic key ，可多值
   * </pre>
   *
   * <code>repeated string topic = 1;</code>
   */
  int getTopicCount();
  /**
   * <pre>
   *具体的topic key ，可多值
   * </pre>
   *
   * <code>repeated string topic = 1;</code>
   */
  java.lang.String getTopic(int index);
  /**
   * <pre>
   *具体的topic key ，可多值
   * </pre>
   *
   * <code>repeated string topic = 1;</code>
   */
  com.google.protobuf.ByteString
      getTopicBytes(int index);

  /**
   * <code>optional .app.ListenTopicReq.Method method = 2;</code>
   */
  int getMethodValue();
  /**
   * <code>optional .app.ListenTopicReq.Method method = 2;</code>
   */
  ListenTopicReq.Method getMethod();
}
