// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

/**
 * Protobuf type {@code app.ListenTopicReply}
 */
public  final class ListenTopicReply extends
    com.google.protobuf.GeneratedMessageLite<
        ListenTopicReply, ListenTopicReply.Builder> implements
    // @@protoc_insertion_point(message_implements:app.ListenTopicReply)
    ListenTopicReplyOrBuilder {
  private ListenTopicReply() {
    topic_ = "";
    data_ = "";
  }
  public static final int TOPIC_FIELD_NUMBER = 1;
  private java.lang.String topic_;
  /**
   * <pre>
   *具体的topic key
   * </pre>
   *
   * <code>optional string topic = 1;</code>
   */
  public java.lang.String getTopic() {
    return topic_;
  }
  /**
   * <pre>
   *具体的topic key
   * </pre>
   *
   * <code>optional string topic = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTopicBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(topic_);
  }
  /**
   * <pre>
   *具体的topic key
   * </pre>
   *
   * <code>optional string topic = 1;</code>
   */
  private void setTopic(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    topic_ = value;
  }
  /**
   * <pre>
   *具体的topic key
   * </pre>
   *
   * <code>optional string topic = 1;</code>
   */
  private void clearTopic() {
    
    topic_ = getDefaultInstance().getTopic();
  }
  /**
   * <pre>
   *具体的topic key
   * </pre>
   *
   * <code>optional string topic = 1;</code>
   */
  private void setTopicBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    topic_ = value.toStringUtf8();
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private java.lang.String data_;
  /**
   * <pre>
   *由业务推送过来的json信息，根据业务不同内部的格式不同
   * </pre>
   *
   * <code>optional string data = 2;</code>
   */
  public java.lang.String getData() {
    return data_;
  }
  /**
   * <pre>
   *由业务推送过来的json信息，根据业务不同内部的格式不同
   * </pre>
   *
   * <code>optional string data = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDataBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(data_);
  }
  /**
   * <pre>
   *由业务推送过来的json信息，根据业务不同内部的格式不同
   * </pre>
   *
   * <code>optional string data = 2;</code>
   */
  private void setData(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    data_ = value;
  }
  /**
   * <pre>
   *由业务推送过来的json信息，根据业务不同内部的格式不同
   * </pre>
   *
   * <code>optional string data = 2;</code>
   */
  private void clearData() {
    
    data_ = getDefaultInstance().getData();
  }
  /**
   * <pre>
   *由业务推送过来的json信息，根据业务不同内部的格式不同
   * </pre>
   *
   * <code>optional string data = 2;</code>
   */
  private void setDataBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    data_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!topic_.isEmpty()) {
      output.writeString(1, getTopic());
    }
    if (!data_.isEmpty()) {
      output.writeString(2, getData());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!topic_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getTopic());
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getData());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static ListenTopicReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ListenTopicReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ListenTopicReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ListenTopicReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ListenTopicReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ListenTopicReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ListenTopicReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ListenTopicReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ListenTopicReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ListenTopicReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ListenTopicReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code app.ListenTopicReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<ListenTopicReply, Builder> implements
      // @@protoc_insertion_point(builder_implements:app.ListenTopicReply)
          ListenTopicReplyOrBuilder {
    // Construct using com.zj.protocol.grpc.ListenTopicReply.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     *具体的topic key
     * </pre>
     *
     * <code>optional string topic = 1;</code>
     */
    public java.lang.String getTopic() {
      return instance.getTopic();
    }
    /**
     * <pre>
     *具体的topic key
     * </pre>
     *
     * <code>optional string topic = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      return instance.getTopicBytes();
    }
    /**
     * <pre>
     *具体的topic key
     * </pre>
     *
     * <code>optional string topic = 1;</code>
     */
    public Builder setTopic(
        java.lang.String value) {
      copyOnWrite();
      instance.setTopic(value);
      return this;
    }
    /**
     * <pre>
     *具体的topic key
     * </pre>
     *
     * <code>optional string topic = 1;</code>
     */
    public Builder clearTopic() {
      copyOnWrite();
      instance.clearTopic();
      return this;
    }
    /**
     * <pre>
     *具体的topic key
     * </pre>
     *
     * <code>optional string topic = 1;</code>
     */
    public Builder setTopicBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTopicBytes(value);
      return this;
    }

    /**
     * <pre>
     *由业务推送过来的json信息，根据业务不同内部的格式不同
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    public java.lang.String getData() {
      return instance.getData();
    }
    /**
     * <pre>
     *由业务推送过来的json信息，根据业务不同内部的格式不同
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      return instance.getDataBytes();
    }
    /**
     * <pre>
     *由业务推送过来的json信息，根据业务不同内部的格式不同
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    public Builder setData(
        java.lang.String value) {
      copyOnWrite();
      instance.setData(value);
      return this;
    }
    /**
     * <pre>
     *由业务推送过来的json信息，根据业务不同内部的格式不同
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    public Builder clearData() {
      copyOnWrite();
      instance.clearData();
      return this;
    }
    /**
     * <pre>
     *由业务推送过来的json信息，根据业务不同内部的格式不同
     * </pre>
     *
     * <code>optional string data = 2;</code>
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDataBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:app.ListenTopicReply)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ListenTopicReply();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        ListenTopicReply other = (ListenTopicReply) arg1;
        topic_ = visitor.visitString(!topic_.isEmpty(), topic_,
            !other.topic_.isEmpty(), other.topic_);
        data_ = visitor.visitString(!data_.isEmpty(), data_,
            !other.data_.isEmpty(), other.data_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                topic_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                data_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (ListenTopicReply.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:app.ListenTopicReply)
  private static final ListenTopicReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ListenTopicReply();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static ListenTopicReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListenTopicReply> PARSER;

  public static com.google.protobuf.Parser<ListenTopicReply> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

