// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

public interface LiveRoomMessageReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:app.LiveRoomMessageReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roomId = 1;</code>
   * @return The roomId.
   */
  int getRoomId();

  /**
   * <code>int64 liveId = 2;</code>
   * @return The liveId.
   */
  long getLiveId();

  /**
   * <code>string msgType = 3;</code>
   * @return The msgType.
   */
  java.lang.String getMsgType();
  /**
   * <code>string msgType = 3;</code>
   * @return The bytes for msgType.
   */
  com.google.protobuf.ByteString
      getMsgTypeBytes();

  /**
   * <code>string content = 4;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 4;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
