// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

public interface MultiLanguageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:app.MultiLanguage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area = 1;</code>
   * @return The area.
   */
  java.lang.String getArea();
  /**
   * <code>string area = 1;</code>
   * @return The bytes for area.
   */
  com.google.protobuf.ByteString
      getAreaBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
