// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

public interface QuestionContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:app.QuestionContent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.app.TextContent textContent = 1;</code>
   * @return Whether the textContent field is set.
   */
  boolean hasTextContent();
  /**
   * <code>.app.TextContent textContent = 1;</code>
   * @return The textContent.
   */
  TextContent getTextContent();
  /**
   * <code>.app.TextContent textContent = 1;</code>
   */
  TextContentOrBuilder getTextContentOrBuilder();

  /**
   * <code>uint32 questionStatus = 2;</code>
   * @return The questionStatus.
   */
  int getQuestionStatus();

  /**
   * <code>uint64 questionId = 3;</code>
   * @return The questionId.
   */
  long getQuestionId();

  /**
   * <code>uint64 spark = 4;</code>
   * @return The spark.
   */
  long getSpark();

  /**
   * <code>uint64 diamond = 5;</code>
   * @return The diamond.
   */
  long getDiamond();

  /**
   * <code>bool published = 6;</code>
   * @return The published.
   */
  boolean getPublished();

  /**
   * <code>uint64 sendTime = 7;</code>
   * @return The sendTime.
   */
  long getSendTime();

  /**
   * <code>uint64 expireTime = 8;</code>
   * @return The expireTime.
   */
  long getExpireTime();

  /**
   * <code>string answerMsgType = 9;</code>
   * @return The answerMsgType.
   */
  java.lang.String getAnswerMsgType();
  /**
   * <code>string answerMsgType = 9;</code>
   * @return The bytes for answerMsgType.
   */
  com.google.protobuf.ByteString
      getAnswerMsgTypeBytes();

  /**
   * <code>string contentType = 10;</code>
   * @return The contentType.
   */
  java.lang.String getContentType();
  /**
   * <code>string contentType = 10;</code>
   * @return The bytes for contentType.
   */
  com.google.protobuf.ByteString
      getContentTypeBytes();
}
