// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

public interface SenderInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:app.SenderInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *发送者id
   * </pre>
   *
   * <code>uint64 senderId = 1;</code>
   * @return The senderId.
   */
  long getSenderId();

  /**
   * <pre>
   *发送者名字
   * </pre>
   *
   * <code>string senderName = 2;</code>
   * @return The senderName.
   */
  java.lang.String getSenderName();
  /**
   * <pre>
   *发送者名字
   * </pre>
   *
   * <code>string senderName = 2;</code>
   * @return The bytes for senderName.
   */
  com.google.protobuf.ByteString
      getSenderNameBytes();

  /**
   * <pre>
   *发送者头像
   * </pre>
   *
   * <code>string senderAvatar = 3;</code>
   * @return The senderAvatar.
   */
  java.lang.String getSenderAvatar();
  /**
   * <pre>
   *发送者头像
   * </pre>
   *
   * <code>string senderAvatar = 3;</code>
   * @return The bytes for senderAvatar.
   */
  com.google.protobuf.ByteString
      getSenderAvatarBytes();

  /**
   * <pre>
   *发送终端类型
   * </pre>
   *
   * <code>string senderPlatform = 4;</code>
   * @return The senderPlatform.
   */
  java.lang.String getSenderPlatform();
  /**
   * <pre>
   *发送终端类型
   * </pre>
   *
   * <code>string senderPlatform = 4;</code>
   * @return The bytes for senderPlatform.
   */
  com.google.protobuf.ByteString
      getSenderPlatformBytes();
}
