// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_api.proto

package com.zj.protocol.grpc;

public interface TextContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:app.TextContent)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>optional string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
